version: '3.9'

# ---------------------------------------------------------------------------
# NETWORKS
#   * internal – невидимая извне, только для сервисов кластера
#   * public   – то, что реально пробрасываем наружу (только gateway)
# ---------------------------------------------------------------------------
networks:
  internal:
    driver: bridge
  public:
    driver: bridge

# ---------------------------------------------------------------------------
# VOLUMES
# ---------------------------------------------------------------------------
volumes:
  pgdata:

# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------
services:
  # ------------------------------ DATABASE ----------------------------------
  postgres:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal          # ⚠️ База не публикуется наружу

  # ------------------------------ MQTT BROKER -------------------------------
  emqx:
    image: emqx/emqx:5.6
    restart: unless-stopped
    env_file: .env
    # Оставляем MQTT-порт наружу ТОЛЬКО при необходимости.
    # Если хотите полностью скрыть брокер, закомментируйте строку ниже.
    ports:
      - "${MQTT_PORT}:1883"    # MQTT (при dev‑режиме)
    networks:
      - internal

  # ------------------------------ ROS SWITCH LOGIC --------------------------
  switch_logic:
    build:
      context: .
      dockerfile: docker/switch_logic/Dockerfile
      target: runtime
    # host‑сеть упрощает DDS. Портов наружу не открывает.
    network_mode: host
    env_file: .env
    depends_on:
      - emqx

  # ------------------------------ TELEMETRY COLLECTOR -----------------------
  collector:
    build:
      context: .
      dockerfile: docker/collector/Dockerfile
      target: runtime
    env_file: .env
    depends_on:
      - postgres
      - emqx
    networks:
      - internal

  # ------------------------------ FASTAPI GATEWAY ---------------------------
  gateway:
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
      target: runtime
    env_file: .env
    ports:
      - "8000:8000"        # Единственная публичная точка
    depends_on:
      - postgres
      - emqx
    networks:
      - internal
      - public
